env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  quotes:
    - error
    - double
  import/extensions: [0, { <js>: "always" }]
