extends:
  - stylelint-config-sass-guidelines
  - stylelint-config-idiomatic-order
  - stylelint-config-prettier
rules:
  order/properties-alphabetical-order:
    - null
  declaration-property-unit-allowed-list:
    font-size:
      - "rem"
      - "em"
  # We use Harry Roberts' BEM dialect as our preferred way to format classes.
  selector-class-pattern: ^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$
